// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 const sidebars = {
  webSidebar: [{ 
    type: "autogenerated", 
    dirName: "." // Remove /docs/ and intro.md
  }],
  appSidebar: [{ 
    type: "autogenerated", 
    dirName: "."    // Remove /docs/ and intro.md
  }],
  adminSidebar: [{ 
    type: "autogenerated", 
    dirName: "."   // Remove /docs/ and intro.md
  }],
  featuresSidebar: [{ 
    type: "autogenerated", 
    dirName: "."  // Remove "./" to avoid confusion
  }],
  changelogSidebar: [{ 
    type: "autogenerated", 
    dirName: "."  // Remove "./" to avoid confusion
  }],
  supportSidebar: [{ 
    type: "autogenerated", 
    dirName: "."  // Remove "./" to avoid confusion
  }],
  
};

export default sidebars;
